### PR TITLE
To biom 2.x

### PR DESCRIPTION
**Pull request by wasade**
**NOT READY FOR MERGE YET**

Tests pass (locally at least), however this does not cover the scripts yet.

I wanted to open the PR so that review could begin as this is shaping up to be quite large. I'm getting some PEP-8 stuff as I go along, but there really is quite a bit to do there. I'm also shedding commented out code.

### CODE REVIEW

**Comment by wasade** [comment]
As a note, `metagenome_contributions.py` is not up to speed for subset loading. This is a bit more complex as the paths for execution depend on the underlying format of the table. The HDF5 loader natively support subset on load, but the JSON one does not. I don't know if we can expect/require this to be HDF5 in that portion of the code, so there might need to be some special-case file handling

PR is still not mergable, still working through the scripts.

**Comment by wasade** [comment]
Still need to resolve subset loading, but I think the main bits are done. 

It is not possible with this code base to ensure things work. There is a lot of complex logic in the scripts, and we do not have script level testing in place. Before this PR is merged, I highly recommend reviewers pull down and test locally.

**Comment by wasade** [comment]
I completely misspoke, I apologize for that. There are script level tests, but I did not notice them before because they weren't executing in my environment (unsure why at this time). This will likely raise some flags, so this is still not ready for review.

I'm still tinkering with travis, hopefully this is the last change necessary

**Comment by wasade** [comment]
More scripts pass locally now. I'm unable to fully utilize the script usage tests as they require non-released datasets (such as ko_18may2012_precalculated.tab.gz).

Nearly finishing taking testing as far as I can. 

@mlangill, would you be able to start on a review? I realize this has grown huge. I started to address some PEP8 issues but pushed that to the side. My editor also removes trailing whitespace, which accounts for a large number of the changes.

**Comment by wasade** [comment]
This PR depends on biocore/biom-format#610, and the pending release of BIOM 2.1.4

**Comment by mlangill** [comment]
@wasade How would you like to proceed here? I have reviewed your commits and they look good. I still need to do some local testing before merging, but should I wait until your biom PR is merged?

**Comment by wasade** [comment]
Thanks, @mlangill. Recommend waiting until BIOM 2.1.4 is merged. I believe there was still at least one outstanding issue or so there but can't look at it right now

**Comment by zaneveld** [comment]
Thanks for the PR @wasade and for reviewing @mlangill-  let me know if
anything is needed / useful on my end.
On a sampling trip in Saudi Arabia so I've only been checking in
infrequently for the last couple of weeks.

**Comment by wasade** [comment]
I think we're now just pending the BIOM 2.1.4 release as biocore/biom-format#610 was merged. I expect the release to happen soon. Double checking tests here in preparation.

**Comment by wasade** [comment]
Just an update on this, I'm still resolving some issues. Before merge, I want to at a minimum be able to run through `normalize_by_copy_number`, `predict_metagenome` and `categorize_by_function`.

**Comment by mlangill** [comment]
@wasade With the release of BIOM 2.1.4 and QIIME 1.9.1 are we ready to try and get this PR merged?

**Comment by wasade** [comment]
Would be great, its been lingering for a while, sorry about that. I'll go
through this PR once more today and refresh

**Comment by wasade** [comment]
There are at least a few more hours here, and possibly another minor release of BIOM. The nested metadata is not formatting correctly, and while I'm not excited about it, I think the easiest thing to do is to add additional special cases in BIOM's HDF5 metadata formatters and parsers. They need a larger overhaul to properly detect `[[str]]` in order to support it. 

Second issue I'm seeing is that the counts from `normalize_by_copy_number.py` are currently off dramatically relative to what picrust 1.0.0 produces. I don't know the source of the error yet. 

I would love to get this finished off as its been open for a while, but I'm defending on the 18th of this month which makes carving time for this very difficult.

**Comment by wasade** [comment]
...github seems down? Very weird. I got this branch I think back in to order for resolving the issues mentioned June 2nd. Would like to get it closed out. Still context switching back into it though.

**Comment by zaneveld** [comment]
Did that do it?

If so- huge congratulations!  That's been a big headache for a while -
thanks for grinding it out Daniel!

**Comment by mlangill** [comment]
No, I jumped the gun! :( I had read Daniel's last commit message wrong and
thought he had solved the previous problems. I tested locally and all tests
passed so thought it was good to go. I have "reverted" the master back to
before the PR from Daniel. Will have to wait for fixes still. Sorry about
that!

Morgan

**Comment by wasade** [comment]
No worries. It's back to being able to be developed on...

**Comment by wasade** [comment]
it looks like it was reverted and then remerged. Not sure what happened.

**Comment by wasade** [comment]
@zaneveld, merging upstream master blows away a lot of extremely painful work.

**Comment by wasade** [comment]
...im just going to open a new pr i guess?

**Comment by wasade** [comment]
nope, a new PR is not getting a correct perspective. I do not know how to get back into a position right now to finish these modifications.

**Pull request merged**
