### PR TITLE
Fixes #195

### LINKED ISSUE #195: categorize_by_function.py is broken BIOM 2.X
categorize_by_function.py runs without errors but results in an empty hdf5 BIOM file.

### PR DESCRIPTION
**Pull request by wasade**
@mlangill, I believe this resolves the problem. Open question though, are there other scripts that consume the predicted output, which will need this duct tape? 

As a reminder, the issue here is that the metadata storage for the current python implementation of biom 2x is less flexible, but I'm hesitant to push changes into biom given that we're slated to migrate the in-memory object to skbio.

### CODE REVIEW

**Comment by wasade** [comment]
ping @mlangill @zaneveld

**Comment by antgonza** [comment]
👍 , can we merge?

**Comment by zaneveld** [comment]
Seems good to go to me.

On Mon, May 16, 2016 at 10:02 AM, Antonio Gonzalez <notifications@github.com

**Comment by wasade** [comment]
Thanks!

**Comment by zaneveld** [comment]
Thank you - much appreciated. Should have a big run coming up for GCMP - in reference to the above question that should use all of the scripts.  If there are any other consumers that need bandaids I'll add an issue (though I think we may now be good)

**Pull request merged**
