### PR TITLE
Updated for v1.1.1

### PR DESCRIPTION
**Pull request by gavinmdouglas**
Added in new html files generated by docs in v1.1.1_update branch.

### CODE REVIEW

**Comment by gavinmdouglas** [comment]
You can see the updated website here: [https://gavinmdouglas.github.io/picrust/](https://gavinmdouglas.github.io/picrust/)

**Comment by mlangill** [comment]
Did you want to add a line for this 1.1.1  release under the News & Announcements heading on the main doc page?

**Comment by gavinmdouglas** [comment]
I was going to do that after the release when I switch the version numbers to 1.1.1-dev, but no big deal either way.


Gavin

**Comment by mlangill** [comment]
Ahhh I see. Ok sounds good.

**Pull request merged**
