### PR TITLE
biom 2x support

### PR DESCRIPTION
**Pull request by wasade**
I think this gets us back to where #171 was

### CODE REVIEW

**Comment by wasade** [comment]
Now to resolve the issue with different data being generated

**Comment by wasade** [comment]
@mlangill, this is now appears to be generating the same results as v1.0.0

**Comment by wasade** [comment]
Just to flag, @gregcaporaso @rob-knight, this PR gets picrust to biom 2x support.

**Comment by gregcaporaso** [comment]
Awesome!

**Comment by zaneveld** [comment]
Great, thanks Daniel!

**Comment by wasade** [comment]
Woo!!

**Pull request merged**
